tasks:
  - name: task-1
    command: echo "Hello"
  - name: task-2
    command: echo "Hello"
  - name: task-3
    command: echo "Hello"
  - name: task-4
    command: echo "Hello"
  - name: task-5
    command: echo "Hello"
  - name: task-6
    command: echo "Hello"
  - name: task-7
    command: echo "Hello"
  - name: task-8
    command: echo "Hello"
  - name: task-9
    command: echo "Hello"
  - name: task-10
    command: echo "Hello"
  - name: task-11
    command: echo "Hello"
  - name: task-12
    command: echo "Hello"
  - name: task-13
    command: echo "Hello"
  - name: task-14
    command: echo "Hello"
  - name: task-15
    command: echo "Hello"
  - name: task-16
    command: echo "Hello"
  - name: task-17
    command: echo "Hello"
  - name: task-18
    command: echo "Hello"
  - name: task-19
    command: echo "Hello"
  - name: task-20
    command: echo "Hello"
  - name: task-21
    command: echo "Hello"
  - name: task-22
    command: echo "Hello"
  - name: task-23
    command: echo "Hello"
  - name: task-24
    command: echo "Hello"
  - name: task-25
    command: echo "Hello"
  - name: task-26
    command: echo "Hello"
  - name: task-27
    command: echo "Hello"
  - name: task-28
    command: echo "Hello"
  - name: task-29
    command: echo "Hello"
  - name: task-30
    command: echo "Hello"
  - name: task-31
    command: echo "Hello"
  - name: task-32
    command: echo "Hello"
  - name: task-33
    command: echo "Hello"
  - name: task-34
    command: echo "Hello"
  - name: task-35
    command: echo "Hello"
  - name: task-36
    command: echo "Hello"
  - name: task-37
    command: echo "Hello"
  - name: task-38
    command: echo "Hello"
  - name: task-39
    command: echo "Hello"
  - name: task-40
    command: echo "Hello"
  - name: task-41
    command: echo "Hello"
  - name: task-42
    command: echo "Hello"
  - name: task-43
    command: echo "Hello"
  - name: task-44
    command: echo "Hello"
  - name: task-45
    command: echo "Hello"
  - name: task-46
    command: echo "Hello"
  - name: task-47
    command: echo "Hello"
  - name: task-48
    command: echo "Hello"
  - name: task-49
    command: echo "Hello"
  - name: task-50
    command: echo "Hello"
  - name: task-51
    command: gp tasks stop --all
