tasks:
  - name: task-1
    command: echo "Hello"
  - name: task-2
    command: echo "Hello"
  - name: task-3
    command: echo "Hello"
  - name: task-4
    command: echo "Hello"
  - name: task-5
    command: echo "Hello"
  - name: task-6
    command: echo "Hello"
  - name: task-7
    command: echo "Hello"
  - name: task-8
    command: echo "Hello"
  - name: task-9
    command: echo "Hello"
  - name: task-10
    command: echo "Hello"
